name: Generate Snake
permissions:
  contents: write

on:
  schedule:
    - cron: "0 */6 * * *"  # every 6 hours
  workflow_dispatch:       # manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate snake SVGs
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            ./output/snake.svg
            ./output/snake-dark.svg?palette=github-dark

      - name: Commit snake images
        uses: EndBug/add-and-commit@v9
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          author_name: 'github-actions[bot]'
          author_email: '41898282+github-actions[bot]@users.noreply.github.com'
          message: 'chore: update snake images'
          add: 'output/snake*.svg'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
