name: WakaTime Readme

on:
  schedule:
    # 每天凌晨4点更新（UTC时间，对应中国时间中午12点）
    - cron: '0 4 * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  update-readme:
    name: Update WakaTime Readme Stats
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROJECTS: "False"
          SHOW_LINES_OF_CODE: "True"
          SHOW_LOC_CHART: "False"
          LOCALE: "zh-CN"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_SHORT_INFO: "False"
          SHOW_TOTAL_CODE_TIME: "True"
          SHOW_UPDATED_DATE: "True" 